### ISSUE TITLE
可以考虑额外放一份原版或其他代理商的购买链接出来

### ISSUE THREAD

**Issue by chenfei0928** [xyjoey/fxxkmakeding#2]
不过我感觉直接将这种poj版整合放出来很容易被DMCA啊
可以考虑额外放一份原版或其他代理商的购买链接出来，引导人去非马克丁版本比较好？
这样肯定不会被DMCA

例如ParagonNTFS，有不只MKD一个代理商，而且也可以到官方购买原版

**Comment by Yanstory** [comment]
附议，可以整理一个官方/官方授权非mkd代理商列表

**Comment by xyjoey** [comment]
空闲的时候加上
